// eslint-disable-next-line import/prefer-default-export
export const PRODUCT_ACTIONS = {
  // Product Data Actions
  SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
  UPDATE_PRODUCT_FIELD: 'UPDATE_PRODUCT_FIELD',
  CLEAR_PRODUCT_DATA: 'CLEAR_PRODUCT_DATA',
  
  // API Data Actions
  SET_API_DATA: 'SET_API_DATA',
  SET_FETCH_PROMISE: 'SET_FETCH_PROMISE',
  CLEAR_FETCH_PROMISE: 'CLEAR_FETCH_PROMISE',
  
  // Tab Selection Actions (per-tab, legacy)
  SET_TAB_SELECTION: 'SET_TAB_SELECTION',
  CLEAR_TAB_SELECTION: 'CLEAR_TAB_SELECTION',
  CLEAR_ALL_TAB_SELECTIONS: 'CLEAR_ALL_TAB_SELECTIONS',
  
  // Global Option Selection Actions (applies to all tabs)
  SET_GLOBAL_OPTION_SELECTION: 'SET_GLOBAL_OPTION_SELECTION',
  CLEAR_GLOBAL_OPTION_SELECTION: 'CLEAR_GLOBAL_OPTION_SELECTION',
  
  // Navigation Actions
  SET_NAVIGATION_TOKEN: 'SET_NAVIGATION_TOKEN',
  SET_CREATING_TOGGLE: 'SET_CREATING_TOGGLE',
  SET_TOGGLE_OPERATION: 'SET_TOGGLE_OPERATION',
};

